print ("Welcome to Madlib")
noun = input ("Pick a random noun")
noun2 = input ("Pick a second random noun")
verb = input ("Pick a random verb")
adjective = input ("Pick a random adjective")
adjective2 = input ("Pick a second random adjective")
adverb = input ("Pick a random adverb")
print ("Here's your Madlib:")
print ( "Doctor " +noun+ " walked to a cat store one day. There he " +verb+ " with seven hippos") 
print ("in front of the store.")
print ("An angry cat with a" +adjective+ " bow ran " +adverb+ " and slapped " +noun+ " with")  
print ("his magic power of awesomeness")
print ("Doctor " +noun+ " began crying and his tears " +adverb+ " took down the cat.")
print ("The " +adjective+ " bow cat's partner " +noun2+ " appeared with his " +adjective2+ " sidekick")
print ("Bobbett" )
print ("Officer " +noun2+ " and Bobbett" +verb+ " and power smacked " +noun+ ".")
print ("Everyone lived happily ever after...")